name: generate profile summary cards

on:
  schedule:
    - cron: "30 0 * * *"   # runs every day at 00:30 UTC
  workflow_dispatch:         # lets you run it manually with the "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
